import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { describe, it } from "node:test";
import { CLI_VERSION } from "../src/version.js";

const run = promisify(execFile);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

async function packageVersion(): Promise<string> {
  const raw = await readFile(resolve(root, "package.json"), "utf8");
  return (JSON.parse(raw) as { version: string }).version;
}

describe("release metadata", () => {
  // The manifest's generator stamp comes from CLI_VERSION, and `vulcanus
  // update` compares it against the vault's. A drifted constant would make
  // every vault claim it was generated by a version that was never published.
  it("keeps CLI_VERSION in step with package.json", async () => {
    assert.equal(CLI_VERSION, await packageVersion());
  });

  it("documents the published version in the changelog", async () => {
    const changelog = await readFile(resolve(root, "CHANGELOG.md"), "utf8");
    const published = await packageVersion();
    // The version under development lives under `## Unreleased` until the
    // release script stamps it, so either heading counts as documented.
    const documented = changelog.includes(`## ${published}`) || /^## Unreleased$/m.test(changelog);
    assert.ok(documented, `CHANGELOG.md mentions neither ${published} nor an Unreleased section`);
  });

  it("bumps every version site in one pass", async () => {
    const { stdout } = await run(
      process.execPath,
      [resolve(root, "scripts/release.mjs"), "minor", "--dry-run"],
      { cwd: root },
    );
    const current = await packageVersion();
    const [major, minor] = current.split(".").map(Number);
    assert.match(stdout, new RegExp(`${current} -> ${major}\\.${minor + 1}\\.0`));
  });

  it("extracts a changelog section for the release notes", async () => {
    const changelog = await readFile(resolve(root, "CHANGELOG.md"), "utf8");
    const released = /^## (\d+\.\d+\.\d+)/m.exec(changelog);
    assert.ok(released, "CHANGELOG.md has no released version section");

    const { stdout } = await run(
      process.execPath,
      [resolve(root, "scripts/changelog-section.mjs"), released[1]],
      { cwd: root },
    );
    assert.ok(stdout.trim().length > 0);
    assert.ok(!stdout.startsWith("## "), "the heading itself must not be part of the notes");
  });
});
