import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { describe, it } from "node:test";
import { nextVersion } from "../scripts/version-bump.mjs";
import { CLI_VERSION } from "../src/version.js";

const run = promisify(execFile);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

async function packageVersion(): Promise<string> {
  const raw = await readFile(resolve(root, "package.json"), "utf8");
  return (JSON.parse(raw) as { version: string }).version;
}

describe("release metadata", () => {
  // The manifest's generator stamp comes from CLI_VERSION, and `vulcanus
  // update` compares it against the vault's. A drifted constant would make
  // every vault claim it was generated by a version that was never published.
  it("keeps CLI_VERSION in step with package.json", async () => {
    assert.equal(CLI_VERSION, await packageVersion());
  });

  it("documents the published version in the changelog", async () => {
    const changelog = await readFile(resolve(root, "CHANGELOG.md"), "utf8");
    const published = await packageVersion();
    // The version under development lives under `## Unreleased` until the
    // release script stamps it, so either heading counts as documented.
    const documented = changelog.includes(`## ${published}`) || /^## Unreleased$/m.test(changelog);
    assert.ok(documented, `CHANGELOG.md mentions neither ${published} nor an Unreleased section`);
  });

  it("resolves a bump keyword or an explicit version", () => {
    assert.equal(nextVersion("0.4.0", "patch"), "0.4.1");
    assert.equal(nextVersion("0.4.1", "minor"), "0.5.0");
    assert.equal(nextVersion("0.5.0", "major"), "1.0.0");
    assert.equal(nextVersion("0.4.0", "1.2.3"), "1.2.3");
    assert.equal(nextVersion("0.4.0", "1.0.0-rc.1"), "1.0.0-rc.1");
    assert.throws(() => nextVersion("0.4.0", "bogus"), /Not a version or bump keyword/);
  });

  // Cutting a release empties the Unreleased section, and the script refuses to
  // release nothing. Both states are correct, so the test asserts whichever one
  // the CHANGELOG is actually in rather than pinning the repository to one.
  it("refuses to cut a release the changelog does not describe", async () => {
    const changelog = await readFile(resolve(root, "CHANGELOG.md"), "utf8");
    const unreleased = /^## Unreleased\n([\s\S]*?)(?=^## |$(?![\s\S]))/m.exec(changelog);
    assert.ok(unreleased, "CHANGELOG.md must keep an `## Unreleased` section");

    const dryRun = run(
      process.execPath,
      [resolve(root, "scripts/release.mjs"), "minor", "--dry-run"],
      {
        cwd: root,
      },
    );

    if (unreleased[1].trim()) {
      const { stdout } = await dryRun;
      const current = await packageVersion();
      assert.match(stdout, new RegExp(`${current} -> ${nextVersion(current, "minor")}`));
      return;
    }

    await assert.rejects(dryRun, /`## Unreleased` section is empty/);
  });

  it("extracts a changelog section for the release notes", async () => {
    const changelog = await readFile(resolve(root, "CHANGELOG.md"), "utf8");
    const released = /^## (\d+\.\d+\.\d+)/m.exec(changelog);
    assert.ok(released, "CHANGELOG.md has no released version section");

    const { stdout } = await run(
      process.execPath,
      [resolve(root, "scripts/changelog-section.mjs"), released[1]],
      { cwd: root },
    );
    assert.ok(stdout.trim().length > 0);
    assert.ok(!stdout.startsWith("## "), "the heading itself must not be part of the notes");
  });
});
