export interface GeneratedFile {
  /** Vault-relative path. */
  path: string;
  content: string;
  /**
   * `managed` files are regenerated by the CLI and safe to overwrite on repair.
   * `seed` files are starting points the operator is expected to edit by hand;
   * they are never overwritten once they exist.
   * `merge` files are both: the CLI owns their structure, but the operator adds
   * to them, so an update adds what is missing instead of replacing the file.
   */
  kind: "managed" | "seed" | "merge";
  /**
   * How to fold the generated content into the operator's existing file. Only
   * consulted for `merge` files that already exist.
   */
  merge?: (existing: string, generated: string) => string;
}
