export interface GeneratedFile {
  /** Vault-relative path. */
  path: string;
  content: string;
  /**
   * `managed` files are regenerated by the CLI and safe to overwrite on repair.
   * `seed` files are starting points the operator is expected to edit by hand;
   * they are never overwritten once they exist.
   */
  kind: "managed" | "seed";
}
