import { readFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { relative, resolve } from "node:path";
import {
  buildPlan,
  hubExpectations,
  recallRouteExpectations,
  returnLinkExpectations,
  type VaultPlan,
} from "../manifest/derive.js";
import { MANIFEST_VERSION, validateManifest, type VaultManifest } from "../manifest/schema.js";
import { parseNote, wikiTargets } from "../util/markdown.js";
import { compareVersions } from "../util/semver.js";
import { CLI_VERSION } from "../version.js";

export type FindingLevel = "error" | "warning" | "info";

export interface DoctorFinding {
  level: FindingLevel;
  code: string;
  message: string;
  file?: string;
}

export interface DoctorReport {
  ok: boolean;
  filesChecked: number;
  linksChecked: number;
  findings: DoctorFinding[];
  counts: Record<FindingLevel, number>;
}

const REQUIRED_FRONTMATTER = ["type", "project", "status", "tags"];

async function collectMarkdown(root: string, dir: string): Promise<string[]> {
  const absolute = resolve(root, dir);
  if (!existsSync(absolute)) return [];

  const out: string[] = [];
  const walk = async (current: string): Promise<void> => {
    const entries = await readdir(current, { withFileTypes: true });
    for (const entry of entries) {
      const full = resolve(current, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (entry.isFile() && entry.name.toLowerCase().endsWith(".md")) {
        out.push(relative(root, full));
      }
    }
  };

  await walk(absolute);
  return out.sort();
}

function baseName(path: string): string {
  return (path.split("/").pop() ?? path).replace(/\.md$/i, "").normalize("NFC");
}

export async function runDoctor(
  vaultRoot: string,
  manifest: VaultManifest,
): Promise<DoctorReport> {
  const findings: DoctorFinding[] = [];
  const add = (level: FindingLevel, code: string, message: string, file?: string) => {
    findings.push({ level, code, message, file });
  };

  for (const issue of validateManifest(manifest)) {
    add(issue.level, "MANIFEST", issue.message);
  }

  // Version drift between the vault and the CLI writing to it.
  if (manifest.manifestVersion > MANIFEST_VERSION) {
    add(
      "error",
      "VERSION",
      `vault manifest is version ${manifest.manifestVersion} but this CLI understands ${MANIFEST_VERSION}; upgrade with \`npm i -g vulcanus@latest\``,
    );
  } else if (compareVersions(manifest.generator.version, CLI_VERSION) < 0) {
    add(
      "warning",
      "VERSION",
      `vault was generated by Vulcanus ${manifest.generator.version}, you are running ${CLI_VERSION}; run \`vulcanus update\``,
    );
  }

  const plan: VaultPlan = buildPlan(manifest);

  const managedDirs = [manifest.structure.systemDir, manifest.structure.projectsDir];
  const files: string[] = [];
  for (const dir of managedDirs) {
    files.push(...(await collectMarkdown(vaultRoot, dir)));
  }

  // Root protocol files are required but live outside the managed note directories.
  for (const required of ["AGENTS.md", "README.md"]) {
    if (!existsSync(resolve(vaultRoot, required))) {
      add("error", "MISSING", `${required} is missing`, required);
    }
  }

  const contents = new Map<string, string>();
  for (const file of files) {
    contents.set(file, await readFile(resolve(vaultRoot, file), "utf8"));
  }

  // --- Planned notes exist -------------------------------------------------
  const present = new Set(files);
  for (const note of plan.allNotes) {
    if (!present.has(note.path)) {
      add("error", "MISSING", `planned note is missing: ${note.path}`, note.path);
    }
  }

  const plannedPaths = new Set(plan.allNotes.map((note) => note.path));
  for (const file of files) {
    if (!plannedPaths.has(file)) {
      add("info", "UNMANAGED", `note is not described by the manifest`, file);
    }
  }

  // --- Frontmatter ---------------------------------------------------------
  for (const file of files) {
    const parsed = parseNote(contents.get(file)!);
    for (const issue of parsed.issues) {
      add("error", "FRONTMATTER", issue, file);
    }
    if (parsed.frontmatterLines === null) continue;

    const duplicates = [...new Set(parsed.keys.filter((key, index) => parsed.keys.indexOf(key) !== index))];
    if (duplicates.length) {
      add("error", "FRONTMATTER", `duplicate keys: ${duplicates.join(", ")}`, file);
    }
    const missing = REQUIRED_FRONTMATTER.filter((key) => !parsed.keys.includes(key));
    if (missing.length) {
      add("error", "FRONTMATTER", `missing keys: ${missing.join(", ")}`, file);
    }
    for (const key of ["type", "project", "status"]) {
      if (parsed.keys.includes(key) && !parsed.values[key]) {
        add("error", "FRONTMATTER", `empty ${key}`, file);
      }
    }
    if (parsed.keys.includes("tags") && parsed.tags.length === 0) {
      add("error", "FRONTMATTER", "tags must contain at least one item", file);
    }
  }

  // --- Link graph ----------------------------------------------------------
  const byStem = new Map<string, string[]>();
  const byCasefold = new Map<string, string[]>();
  for (const file of files) {
    const stem = baseName(file);
    byStem.set(stem, [...(byStem.get(stem) ?? []), file]);
    const folded = stem.toLowerCase();
    byCasefold.set(folded, [...(byCasefold.get(folded) ?? []), file]);
  }

  for (const [stem, paths] of byStem) {
    if (paths.length > 1) {
      add("error", "DUPLICATE", `duplicate note name "${stem}": ${paths.join(", ")}`);
    }
  }
  for (const [stem, paths] of byCasefold) {
    if (paths.length > 1 && new Set(paths.map(baseName)).size > 1) {
      add(
        "error",
        "CASEFOLD",
        `note names differ only by case ("${stem}"): ${paths.join(", ")}`,
      );
    }
  }

  const resolveTarget = (source: string, target: string): string[] => {
    const normalized = target.replace(/\.md$/i, "");
    const direct = `${normalized}.md`;
    const matches = new Set<string>();

    if (present.has(direct)) matches.add(direct);
    const stem = baseName(normalized);
    for (const path of byStem.get(stem) ?? []) matches.add(path);

    // Relative to the linking note's own directory.
    const sourceDir = source.split("/").slice(0, -1).join("/");
    const relativeCandidate = sourceDir ? `${sourceDir}/${direct}` : direct;
    if (present.has(relativeCandidate)) matches.add(relativeCandidate);

    return [...matches];
  };

  let linksChecked = 0;
  for (const file of files) {
    for (const target of wikiTargets(contents.get(file)!)) {
      linksChecked += 1;
      const matches = resolveTarget(file, target);
      if (matches.length === 0) {
        add("error", "BROKEN", `link target not found: [[${target}]]`, file);
      } else if (matches.length > 1) {
        add("error", "AMBIGUOUS", `[[${target}]] resolves to ${matches.join(", ")}`, file);
      }
    }
  }

  // --- Hub coverage --------------------------------------------------------
  const targetsOf = new Map<string, Set<string>>();
  for (const file of files) {
    targetsOf.set(file, new Set(wikiTargets(contents.get(file)!)));
  }

  for (const [path, expected] of hubExpectations(plan)) {
    const actual = targetsOf.get(path);
    if (!actual) continue; // already reported as missing
    const missing = [...expected].filter((name) => !actual.has(name));
    if (missing.length) {
      add("error", "HUB", `missing links: ${missing.join(", ")}`, path);
    }
    const extra = [...actual].filter((name) => !expected.has(name));
    if (extra.length) {
      add("warning", "HUB", `links beyond the manifest: ${extra.join(", ")}`, path);
    }
  }

  // --- Return links --------------------------------------------------------
  for (const [path, hubName] of returnLinkExpectations(plan)) {
    const actual = targetsOf.get(path);
    if (!actual) continue;
    if (!actual.has(hubName)) {
      add("error", "RETURN", `does not link back to ${hubName}`, path);
    }
  }

  // --- Capsule and Recall Map coverage -------------------------------------
  const recallTargets = targetsOf.get(plan.recallMap.path);
  if (recallTargets) {
    for (const name of recallRouteExpectations(plan)) {
      if (!recallTargets.has(name)) {
        add("error", "RECALL", `no recall route to ${name}`, plan.recallMap.path);
      }
    }
  }

  for (const project of plan.allProjects) {
    const parsed = present.has(project.capsule.path)
      ? parseNote(contents.get(project.capsule.path)!)
      : null;
    if (parsed && parsed.values.type !== "capsule") {
      add(
        "error",
        "CAPSULE",
        `frontmatter type is "${parsed.values.type ?? ""}", expected "capsule"`,
        project.capsule.path,
      );
    }
    const hubTargets = targetsOf.get(project.hub.path);
    if (hubTargets && !hubTargets.has(project.capsule.name)) {
      add("error", "CAPSULE", `hub does not link to ${project.capsule.name}`, project.hub.path);
    }
  }

  // --- Ignore rules --------------------------------------------------------
  const gitignorePath = resolve(vaultRoot, ".gitignore");
  if (existsSync(gitignorePath)) {
    const gitignore = await readFile(gitignorePath, "utf8");
    if (!gitignore.includes(manifest.structure.importsDir)) {
      add("error", "IGNORE", `.gitignore does not ignore ${manifest.structure.importsDir}/`);
    }
    if (!gitignore.includes(manifest.structure.stateDir)) {
      add("warning", "IGNORE", `.gitignore does not ignore ${manifest.structure.stateDir}/`);
    }
  } else {
    add("error", "IGNORE", ".gitignore is missing; raw exports could be committed");
  }

  const counts: Record<FindingLevel, number> = { error: 0, warning: 0, info: 0 };
  for (const finding of findings) counts[finding.level] += 1;

  return {
    ok: counts.error === 0,
    filesChecked: files.length,
    linksChecked,
    findings,
    counts,
  };
}
